- name: Restart Prometheus
  service:
    name: prometheus
    state: restarted

- name: Restart Postgres exporter
  service:
    name: prometheus-postgres-exporter
    state: restarted

- name: Restart node exporter
  service:
    name: prometheus-node-exporter
    state: restarted

- name: Reload systemd daemon
  systemd_service:
    daemon_reload: true
